# Generated by Django 3.2.6 on 2022-04-01 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mentor', '0001_initial'),
        ('estudiante', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(blank=True, null=True, verbose_name=['%y-%m-%d'])),
                ('tipo', models.CharField(choices=[('PL', 'Psicologia'), ('MT', 'Mentoria'), ('AM', 'Academica')], default='', max_length=2)),
                ('estudiante', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='estudiante.estudiante')),
                ('mentor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mentor.mentor')),
            ],
        ),
    ]
