# Generated by Django 3.2.6 on 2022-04-05 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='estudiante',
        ),
        migrations.AddField(
            model_name='reserva',
            name='nombre_estudiante',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
