# Generated by Django 3.2.6 on 2022-04-07 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='estudiante',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
