# Generated by Django 3.2.6 on 2022-04-02 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0001_initial'),
        ('reservas', '0002_remove_reserva_estudiante'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='estudiante',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='estudiante.estudiante'),
        ),
    ]
