# Generated by Django 3.2.6 on 2022-04-02 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_auto_20220402_0859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='estu',
            new_name='estudiane',
        ),
    ]
