# Generated by Django 3.2.6 on 2022-04-05 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0002_remove_mentor_area_especializacion'),
        ('reservas', '0005_rename_estu_reserva_estudiane'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='id',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='mentor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mentor.mentor'),
        ),
    ]
