# Generated by Django 3.2.6 on 2022-04-07 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='area_especializacion',
        ),
    ]
