# Generated by Django 3.2.6 on 2022-04-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0002_remove_mentor_area_especializacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
