# Generated by Django 3.2.6 on 2022-04-01 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pregunta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test_Vocacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testDate', models.DateTimeField(auto_now_add=True)),
                ('questions', models.ManyToManyField(default=None, to='pregunta.Pregunta')),
            ],
        ),
    ]
