# Generated by Django 3.2.6 on 2022-04-06 21:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('test_vocacional', '0002_auto_20220405_1008'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='TestUsuario',
        ),
    ]
