# Generated by Django 3.2.6 on 2022-04-06 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_vocacional', '0004_rename_usuario_preguntasrespondidas_testusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='max_puntaje',
            field=models.DecimalField(decimal_places=2, default=3, max_digits=6, verbose_name='Máximo puntaje'),
        ),
        migrations.AlterField(
            model_name='elegirrespuesta',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='test_vocacional.pregunta'),
        ),
    ]
