# Generated by Django 3.2.6 on 2022-04-06 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_vocacional', '0006_alter_preguntasrespondidas_testusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntasrespondidas',
            name='respuesta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='test_vocacional.elegirrespuesta'),
        ),
    ]
