# Generated by Django 3.2.6 on 2022-04-07 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_vocacional', '0002_auto_20220406_2035'),
        ('pregunta', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pregunta',
        ),
        migrations.DeleteModel(
            name='Respuesta',
        ),
    ]
