# Generated by Django 3.2.6 on 2022-04-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pregunta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='tipo',
            field=models.CharField(choices=[('P1', '¿pregunnta 1?'), ('P2', '¿pregunnta 2?'), ('P3', '¿pregunnta 3?'), ('P4', '¿pregunnta 4?'), ('P5', '¿pregunnta 5?')], default='', max_length=2),
        ),
    ]
