# Generated by Django 3.2.6 on 2022-04-02 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pregunta', '0002_pregunta_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregunta',
            name='text',
        ),
    ]
