# Generated by Django 3.2.6 on 2022-04-05 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pregunta', '0003_remove_pregunta_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elegir_Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correcta', models.BooleanField(default=False, verbose_name='¿Es esta la pregunta correcta?')),
                ('texto', models.TextField(verbose_name='Texto de la respuesta')),
            ],
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='tipo',
        ),
        migrations.AddField(
            model_name='pregunta',
            name='texto',
            field=models.TextField(default=None, verbose_name='Texto de la pregunta'),
        ),
        migrations.DeleteModel(
            name='Respuesta',
        ),
        migrations.AddField(
            model_name='elegir_respuesta',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='pregunta.pregunta'),
        ),
    ]
