# Generated by Django 3.2.6 on 2022-04-05 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pregunta', '0004_auto_20220405_0733'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Elegir_Respuesta',
            new_name='ElegirRespuesta',
        ),
    ]
